// images
import blogImg1 from "../images/blog/img-1.jpg";
import blogImg2 from "../images/blog/img-2.jpg";
import blogImg3 from "../images/blog/img-3.jpg";

import blogSingleImg1 from "../images/blog-details/1.jpg";
import blogSingleImg2 from "../images/blog-details/2.jpg";
import blogSingleImg3 from "../images/blog-details/3.jpg";

// Indeks wpisow: pietnascie ostatnich artykulow z biurodgc.pl/porady/
// (strony 1-3 starego bloga), przepisane 1:1. Tytuly, daty i pierwsze zdania
// pochodza z artykulow DGC, nic tu nie jest wymyslone. Pelna tresc kazdego
// wpisu lezy w blogContent.js pod tym samym slugiem.
//
// Slugi celowo takie same jak na starej stronie, zeby po przeniesieniu domeny
// stare adresy dalej dzialaly i nie przepadly pozycje w Google.
//
// Zdjecia zostaja szablonowe i powtarzaja sie co trzy wpisy — klient podmieni
// je pozniej.
//
// `tag` to kategoria wpisu. Wartosci pochodza z listy kategorii biurodgc.pl
// (CIT, Kadry, Księgowość, PIT, Podatki, Płace, Rachunkowość, VAT). Sama
// strona nie pokazuje, ktora kategoria jest przypisana do ktorego artykulu,
// wiec przypisalem je po tresci. Widget kategorii i filtr miesiaca licza wpisy
// z tych pol, wiec liczby sa prawdziwe i same sie zaktualizuja.

const blogs = [
    {
        id: '1',
        title: 'Rezerwy i odpisy aktualizujące – kiedy je tworzyć',
        title2: 'Rezerwy i odpisy aktualizujące – kiedy je tworzyć',
        tag: 'Rachunkowość',
        slug: 'rezerwy-odpisy',
        screens: blogImg1,
        description: 'Jednym z podstawowych obowiązków jednostek prowadzących księgi rachunkowe jest prezentowanie rzeczywistej sytuacji majątkowej i finansowej przedsiębiorstwa. W księgach nie można wykazywać aktywów w zawyżonej wartości ani pomijać przewidywanych zobowiązań i ryzyk gospodarczych.',
        author: 'DGC Biuro Rachunkowe',
        create_at: '2 września 2026',
        archiveMonth: '2026-09',
        archiveLabel: 'Wrzesień 2026',
        blogSingleImg: blogSingleImg1,
        blClass: 'format-standard-image',
        animation: '1200',
    },
    {
        id: '2',
        title: 'Dotacje i subwencje w księgach rachunkowych',
        title2: 'Dotacje i subwencje w księgach rachunkowych',
        tag: 'Rachunkowość',
        slug: 'ksiegowanie-dotacji',
        screens: blogImg2,
        description: 'Dotacje unijne, środki z urzędów pracy, subwencje i dofinansowania inwestycji to dla wielu firm istotne źródło finansowania. Samo otrzymanie środków nie oznacza jednak, że należy wykazać je jako przychód bieżącego okresu.',
        author: 'DGC Biuro Rachunkowe',
        create_at: '31 sierpnia 2026',
        archiveMonth: '2026-08',
        archiveLabel: 'Sierpień 2026',
        blogSingleImg: blogSingleImg2,
        blClass: 'format-standard-image',
        animation: '1200',
    },
    {
        id: '3',
        title: 'Koszty przyszłych okresów – rozliczenia międzyokresowe',
        title2: 'Koszty przyszłych okresów – rozliczenia międzyokresowe',
        tag: 'Rachunkowość',
        slug: 'rozliczenia-miedzyokresowe-kosztow',
        screens: blogImg3,
        description: 'Przedsiębiorcy często otrzymują faktury dotyczące kilku miesięcy lub nawet lat i błędnie ujmują cały wydatek jednorazowo w kosztach. Takie postępowanie zniekształca wynik finansowy i narusza zasady ustawy o rachunkowości.',
        author: 'DGC Biuro Rachunkowe',
        create_at: '26 sierpnia 2026',
        archiveMonth: '2026-08',
        archiveLabel: 'Sierpień 2026',
        blogSingleImg: blogSingleImg3,
        blClass: 'format-standard-image',
        animation: '1200',
    },
    {
        id: '4',
        title: 'Najczęstsze błędy przy zamknięciu roku obrotowego',
        title2: 'Najczęstsze błędy przy zamknięciu roku obrotowego',
        tag: 'Rachunkowość',
        slug: 'zamkniecie-roku-bledy',
        screens: blogImg1,
        description: 'Samo formalne zamknięcie ksiąg nie wystarczy. Konieczny jest szereg czynności weryfikacyjnych, które pozwolą wykazać wszystkie aktywa, pasywa, przychody i koszty zgodnie z ich rzeczywistą wartością.',
        author: 'DGC Biuro Rachunkowe',
        create_at: '24 sierpnia 2026',
        archiveMonth: '2026-08',
        archiveLabel: 'Sierpień 2026',
        blogSingleImg: blogSingleImg1,
        blClass: 'format-standard-image',
        animation: '1200',
    },
    {
        id: '5',
        title: 'Wynajęcie mieszkania na firmę – obowiązki najemcy',
        title2: 'Wynajęcie mieszkania na firmę – obowiązki najemcy',
        tag: 'Podatki',
        slug: 'wynajem-mieszkania-firmie-najemca',
        screens: blogImg2,
        description: 'Wynajęcie mieszkania na firmę nie oznacza jednego, prostego skutku podatkowego. To cel najmu decyduje o kosztach podatkowych, VAT i dokumentach. Inaczej wygląda lokal dla pracownika, inaczej biuro.',
        author: 'DGC Biuro Rachunkowe',
        create_at: '19 sierpnia 2026',
        archiveMonth: '2026-08',
        archiveLabel: 'Sierpień 2026',
        blogSingleImg: blogSingleImg2,
        blClass: 'format-standard-image',
        animation: '1200',
    },
    {
        id: '6',
        title: 'Dokument SAD – kto go tworzy i kiedy powstaje',
        title2: 'Dokument SAD – kto go tworzy i kiedy powstaje',
        tag: 'VAT',
        slug: 'dokument-sad',
        screens: blogImg3,
        description: 'Jednolity Dokument Administracyjny to podstawowy dokument zgłoszenia celnego w obrocie z krajami spoza Unii. Dla księgowości jest kluczowym dowodem przy rozliczaniu cła oraz VAT z tytułu importu.',
        author: 'DGC Biuro Rachunkowe',
        create_at: '17 sierpnia 2026',
        archiveMonth: '2026-08',
        archiveLabel: 'Sierpień 2026',
        blogSingleImg: blogSingleImg3,
        blClass: 'format-standard-image',
        animation: '1200',
    },
    {
        id: '7',
        title: 'Podatek od nieruchomości – IN-1, DN-1 i kto dostaje decyzję',
        title2: 'Podatek od nieruchomości – IN-1, DN-1 i kto dostaje decyzję',
        tag: 'Podatki',
        slug: 'podatek-od-nieruchomosci',
        screens: blogImg1,
        description: 'To jedna z najważniejszych danin lokalnych i jednocześnie jedna z tych, przy których przedsiębiorcy popełniają najwięcej błędów formalnych. Osoba fizyczna składa IN-1, osoba prawna DN-1, a skutki są różne.',
        author: 'DGC Biuro Rachunkowe',
        create_at: '12 sierpnia 2026',
        archiveMonth: '2026-08',
        archiveLabel: 'Sierpień 2026',
        blogSingleImg: blogSingleImg1,
        blClass: 'format-standard-image',
        animation: '1200',
    },
    {
        id: '8',
        title: 'Opłata produktowa – kto rozlicza i kiedy sprawozdanie',
        title2: 'Opłata produktowa – kto rozlicza i kiedy sprawozdanie',
        tag: 'Podatki',
        slug: 'oplata-produktowa',
        screens: blogImg2,
        description: 'Opłata produktowa dotyczy firm wprowadzających produkty w opakowaniach i jest rozliczana z udziałem marszałka województwa. Pojawia się wtedy, gdy podmiot nie wykonuje ustawowych poziomów odzysku i recyklingu.',
        author: 'DGC Biuro Rachunkowe',
        create_at: '10 sierpnia 2026',
        archiveMonth: '2026-08',
        archiveLabel: 'Sierpień 2026',
        blogSingleImg: blogSingleImg2,
        blClass: 'format-standard-image',
        animation: '1200',
    },
    {
        id: '9',
        title: 'System SENT – dla kogo jest i kto musi z niego korzystać',
        title2: 'System SENT – dla kogo jest i kto musi z niego korzystać',
        tag: 'Podatki',
        slug: 'system-sent',
        screens: blogImg3,
        description: 'System Elektronicznego Nadzoru Transportu nie dotyczy wszystkich przewozów, tylko tych objętych monitorowaniem. Od 17 marca 2026 r. obejmuje także określone przewozy odzieży i obuwia.',
        author: 'DGC Biuro Rachunkowe',
        create_at: '5 sierpnia 2026',
        archiveMonth: '2026-08',
        archiveLabel: 'Sierpień 2026',
        blogSingleImg: blogSingleImg3,
        blClass: 'format-standard-image',
        animation: '1200',
    },
    {
        id: '10',
        title: 'Podatek leśny – kto płaci i kto składa IL-1 albo DL-1',
        title2: 'Podatek leśny – kto płaci i kto składa IL-1 albo DL-1',
        tag: 'Podatki',
        slug: 'podatek-lesny',
        screens: blogImg1,
        description: 'Podatek leśny bywa mylony z podatkiem od nieruchomości albo traktowany jako marginalny obowiązek. Wszystko zaczyna się od klasyfikacji gruntu w ewidencji, a dopiero potem są formularze i terminy.',
        author: 'DGC Biuro Rachunkowe',
        create_at: '3 sierpnia 2026',
        archiveMonth: '2026-08',
        archiveLabel: 'Sierpień 2026',
        blogSingleImg: blogSingleImg1,
        blClass: 'format-standard-image',
        animation: '1200',
    },
    {
        id: '11',
        title: 'Hodowla pająków na sprzedaż – jak ją opodatkować',
        title2: 'Hodowla pająków na sprzedaż – jak ją opodatkować',
        tag: 'PIT',
        slug: 'hodowla-pajakow-podatki',
        screens: blogImg2,
        description: 'Podatkowo najbardziej złożona spośród hodowli zwierząt egzotycznych, bo przepisy nie wymieniają pająków wprost. Najpierw trzeba ustalić, czy to dział specjalny, działalność rolnicza, czy zwykła działalność gospodarcza.',
        author: 'DGC Biuro Rachunkowe',
        create_at: '27 lipca 2026',
        archiveMonth: '2026-07',
        archiveLabel: 'Lipiec 2026',
        blogSingleImg: blogSingleImg2,
        blClass: 'format-standard-image',
        animation: '1200',
    },
    {
        id: '12',
        title: 'Opłaty środowiskowe – wykaz, progi i kiedy nie trzeba płacić',
        title2: 'Opłaty środowiskowe – wykaz, progi i kiedy nie trzeba płacić',
        tag: 'Podatki',
        slug: 'oplaty-srodowiskowe-wykaz-progi',
        screens: blogImg3,
        description: 'Opłaty za korzystanie ze środowiska rozlicza się wobec marszałka województwa, a nie gminy. Nie ma decyzji wymiarowej z urzędu: podmiot sam ustala zakres korzystania ze środowiska i sam przygotowuje wykaz.',
        author: 'DGC Biuro Rachunkowe',
        create_at: '22 lipca 2026',
        archiveMonth: '2026-07',
        archiveLabel: 'Lipiec 2026',
        blogSingleImg: blogSingleImg3,
        blClass: 'format-standard-image',
        animation: '1200',
    },
    {
        id: '13',
        title: 'Opłata paliwowa – kto płaci, formularz OPAL i dlaczego to nie podatek lokalny',
        title2: 'Opłata paliwowa – kto płaci, formularz OPAL i dlaczego to nie podatek lokalny',
        tag: 'Podatki',
        slug: 'oplata-paliwowa-opal',
        screens: blogImg1,
        description: 'Opłata paliwowa bywa wrzucana do jednego worka z podatkami lokalnymi, ale to zupełnie inna danina. Stanowi przychód Krajowego Funduszu Drogowego i Funduszu Kolejowego, a nie budżetu gminy.',
        author: 'DGC Biuro Rachunkowe',
        create_at: '22 lipca 2026',
        archiveMonth: '2026-07',
        archiveLabel: 'Lipiec 2026',
        blogSingleImg: blogSingleImg1,
        blClass: 'format-standard-image',
        animation: '1200',
    },
    {
        id: '14',
        title: 'Efektywna stopa opodatkowania w CIT estońskim – w praktyce',
        title2: 'Efektywna stopa opodatkowania w CIT estońskim – w praktyce',
        tag: 'CIT',
        slug: 'cit-estonski-efektywna-stopa',
        screens: blogImg2,
        description: 'Ile realnie wynosi łączne opodatkowanie spółki i wspólnika? Ryczałt to 10% albo 20%, ale przy wypłacie zysku dochodzi PIT wspólnika, a mechanizm odliczenia decyduje o faktycznej efektywnej stopie.',
        author: 'DGC Biuro Rachunkowe',
        create_at: '15 lipca 2026',
        archiveMonth: '2026-07',
        archiveLabel: 'Lipiec 2026',
        blogSingleImg: blogSingleImg2,
        blClass: 'format-standard-image',
        animation: '1200',
    },
    {
        id: '15',
        title: 'Składki preferencyjne 2026 – przez ile czasu i kto ma prawo',
        title2: 'Składki preferencyjne 2026 – przez ile czasu i kto ma prawo',
        tag: 'Kadry',
        slug: 'skladki-preferencyjne-2026',
        screens: blogImg3,
        description: 'Przez 24 pełne miesiące przedsiębiorca może opłacać składki społeczne od obniżonej podstawy. W 2026 r. to 1 441,80 zł. Najwięcej błędów pojawia się przy liczeniu, od kiedy te 24 miesiące biegną.',
        author: 'DGC Biuro Rachunkowe',
        create_at: '13 lipca 2026',
        archiveMonth: '2026-07',
        archiveLabel: 'Lipiec 2026',
        blogSingleImg: blogSingleImg3,
        blClass: 'format-standard-image',
        animation: '1200',
    },
];

export default blogs;
