// Pelna tresc artykulow z biurodgc.pl/porady/, przepisana 1:1.
// Klucz to slug wpisu z blogs.js.
//
// Bloki:
//   { t: 'h',     x: 'nagłówek' }
//   { t: 'p',     x: 'akapit' }
//   { t: 'ul',    x: ['pozycja', ...] }
//   { t: 'uwaga', h: 'nagłówek ramki', x: 'treść' }  // wyroznione pudelko
//   { t: 'zrodlo', x: 'podstawa prawna' }            // stopka artykulu
//
// Czesc tekstow ma na koncu akapit "DGC Biuro Rachunkowe" pisany w pierwszej
// osobie ("pomagam firmom…"). To material zrodlowy DGC — zostawiam jak jest,
// bo to ich glos, a nie moje streszczenie.

const tresci = {

    'rezerwy-odpisy': [
        { t: 'p', x: 'Jednym z podstawowych obowiązków jednostek prowadzących księgi rachunkowe jest prezentowanie rzeczywistej sytuacji majątkowej i finansowej przedsiębiorstwa. Oznacza to, że w księgach nie można wykazywać aktywów w zawyżonej wartości ani pomijać przewidywanych zobowiązań i ryzyk gospodarczych. Właśnie temu służą rezerwy oraz odpisy aktualizujące.' },
        { t: 'uwaga', h: 'Zasada ostrożności', x: 'Art. 7 ust. 1 ustawy o rachunkowości nakazuje uwzględnić wszystkie zmniejszenia wartości aktywów oraz wszystkie znane ryzyka i grożące straty. Firma nie może czekać na wystąpienie szkody — już samo prawdopodobieństwo powstania straty może wymagać rezerwy albo odpisu.' },
        { t: 'h', x: 'Rezerwa czy odpis – podstawowa różnica' },
        { t: 'p', x: 'Rezerwy dotyczą przyszłych zobowiązań (sprawy sądowe, gwarancje, restrukturyzacja, urlopy), podczas gdy odpisy aktualizujące dotyczą istniejących składników majątku (należności, zapasy, środki trwałe, inwestycje).' },
        { t: 'h', x: 'Najczęstsze rezerwy w praktyce' },
        { t: 'p', x: 'Niewykorzystane urlopy, sprawy sądowe i badanie sprawozdania wymagają odpisów i rezerw odpowiadających rzeczywistym zobowiązaniom.' },
        { t: 'h', x: 'Odpisy aktualizujące należności' },
        { t: 'p', x: 'Art. 35b ustawy o rachunkowości wymaga odpisów przy dłużnikach w likwidacji lub upadłości, należnościach kwestionowanych i przeterminowanych.' },
        { t: 'h', x: 'Odpisy na zapasy i środki trwałe' },
        { t: 'p', x: 'Zapasy wycenia się nie wyżej niż według cen sprzedaży netto możliwych do uzyskania. Środki trwałe wymagają analizy przy trwałym uszkodzeniu lub utracie przydatności.' },
        { t: 'h', x: 'Najczęstsze błędy przedsiębiorców' },
        { t: 'p', x: 'Brak analizy należności, pomijanie rezerw na urlopy i spory, brak analizy utraty wartości zapasów prowadzą do zawyżonego wyniku finansowego.' },
    ],

    'ksiegowanie-dotacji': [
        { t: 'p', x: 'Dotacje unijne, środki z urzędów pracy, subwencje, dofinansowania inwestycji czy wsparcie z funduszy publicznych stanowią dla wielu przedsiębiorców istotne źródło finansowania działalności. Samo otrzymanie środków nie oznacza jednak, że należy je automatycznie wykazać jako przychód bieżącego okresu. Sposób ujęcia dotacji w księgach rachunkowych zależy przede wszystkim od celu, na jaki zostały przyznane środki. Inaczej rozlicza się dotacje przeznaczone na zakup środków trwałych, a inaczej środki finansujące bieżącą działalność operacyjną.' },
        { t: 'uwaga', h: 'Ważne', x: 'Art. 41 ust. 1 pkt 2 ustawy o rachunkowości: do rozliczeń międzyokresowych przychodów zalicza się środki otrzymane na sfinansowanie nabycia lub wytworzenia środków trwałych oraz wartości niematerialnych i prawnych. Wpływ na konto nie równa się przychodowi.' },
        { t: 'h', x: 'Dotacje na zakup środków trwałych' },
        { t: 'p', x: 'Przy dotacjach na maszyny, urządzenia, samochody, linie produkcyjne, budynki czy WNiP otrzymane środki nie stanowią jednorazowo przychodu operacyjnego. Ujmuje się je jako rozliczenia międzyokresowe przychodów, a następnie sukcesywnie odnosi do pozostałych przychodów operacyjnych proporcjonalnie do odpisów amortyzacyjnych. Wynika to z zasady współmierności z art. 6 ustawy o rachunkowości.' },
        { t: 'h', x: 'Przykład – dotacja na maszynę' },
        { t: 'p', x: 'Spółka otrzymała 500 000 zł dotacji na zakup maszyny o wartości 1 000 000 zł, amortyzowanej przez 10 lat. Przychód z dotacji rozpoznawany jest stopniowo przez cały okres amortyzacji, a nie jednorazowo w momencie wpływu środków.' },
        { t: 'h', x: 'Dotacje na bieżącą działalność' },
        { t: 'p', x: 'Inaczej wygląda sytuacja przy środkach na pokrycie bieżących kosztów: refundacjach wynagrodzeń, dopłatach do szkoleń, wsparciu kosztów energii, dofinansowaniu działalności badawczo-rozwojowej. W takich przypadkach przychód ujmuje się w okresie, którego dotyczą finansowane koszty, aby zachować współmierność przychodów i kosztów.' },
        { t: 'ul', x: ['Środki trwałe i WNiP: rozliczenia międzyokresowe przychodów, przychód proporcjonalnie do amortyzacji', 'Bieżąca działalność operacyjna: przychód w okresie finansowanych kosztów'] },
        { t: 'h', x: 'Dotacje unijne – dodatkowe obowiązki ewidencyjne' },
        { t: 'p', x: 'Umowy o dofinansowanie bardzo często wymagają wyodrębnienia ewidencji księgowej projektu, prowadzenia odrębnych kont analitycznych, identyfikacji kosztów kwalifikowanych oraz dokumentowania wydatków zgodnie z wytycznymi instytucji finansującej. Brak odpowiedniej ewidencji może skutkować koniecznością zwrotu części lub całości otrzymanej dotacji.' },
        { t: 'h', x: 'Kiedy powstaje przychód z dotacji' },
        { t: 'p', x: 'W rachunkowości decydujące znaczenie ma ekonomiczny cel dotacji, a nie moment wpływu środków na rachunek bankowy. Wpływ nie zawsze oznacza powstanie przychodu, część dotacji może być rozliczana przez wiele lat, a przychód ujmuje się zgodnie z przeznaczeniem otrzymanych środków. Pomocą dla księgowych są stanowiska Komitetu Standardów Rachunkowości, a dla jednostek stosujących MSR dodatkowo MSR 20 regulujący ujmowanie dotacji rządowych.' },
        { t: 'h', x: 'Najczęstsze błędy przy księgowaniu dotacji' },
        { t: 'ul', x: ['Ujmowanie całej dotacji jednorazowo w przychodach', 'Brak rozliczeń międzyokresowych przychodów i błędne powiązanie dotacji z amortyzacją', 'Brak wyodrębnionej ewidencji projektów unijnych i błędne ujmowanie wydatków kwalifikowanych', 'Brak analizy warunków umowy o dofinansowanie'] },
        { t: 'p', x: 'Prawidłowe rozliczenie dotacji wymaga nie tylko znajomości ustawy o rachunkowości, ale również analizy warunków przyznania środków i celu, na jaki zostały przeznaczone. W DGC wspieram spółki, fundacje i stowarzyszenia w rozliczaniu dotacji unijnych, subwencji i dofinansowań tak, aby księgi, sprawozdania i rozliczenia projektów były zgodne z przepisami i gotowe na kontrolę instytucji finansującej.' },
        { t: 'zrodlo', x: 'Ustawa z 29 września 1994 r. o rachunkowości, art. 4 ust. 1, art. 6 oraz art. 41 ust. 1 pkt 2 · Stanowiska Komitetu Standardów Rachunkowości dotyczące pomocy publicznej · MSR 20 dla jednostek stosujących MSR.' },
    ],

    'rozliczenia-miedzyokresowe-kosztow': [
        { t: 'p', x: 'Jednym z podstawowych obowiązków jednostek prowadzących księgi rachunkowe jest prawidłowe przyporządkowanie kosztów do okresów, których dotyczą. W praktyce przedsiębiorcy często otrzymują faktury dotyczące kilku miesięcy lub nawet kilku lat i błędnie ujmują cały wydatek jednorazowo w kosztach. Takie postępowanie może prowadzić do zniekształcenia wyniku finansowego oraz naruszenia zasad rachunkowości określonych w ustawie o rachunkowości.' },
        { t: 'uwaga', h: 'Zasada współmierności', x: 'Art. 6 ust. 2 ustawy o rachunkowości wymaga, aby do aktywów lub pasywów danego okresu zaliczać koszty dotyczące przyszłych okresów oraz koszty przypadające na ten okres, które jeszcze nie zostały poniesione. Koszt obciąża wynik tego okresu, którego faktycznie dotyczy, niezależnie od daty faktury czy zapłaty.' },
        { t: 'h', x: 'Czynne rozliczenia międzyokresowe kosztów' },
        { t: 'p', x: 'Zgodnie z art. 39 ust. 1 ustawy o rachunkowości jednostki dokonują czynnych rozliczeń międzyokresowych kosztów, jeżeli dotyczą one przyszłych okresów sprawozdawczych. Wydatki poniesione z góry, które będą przynosiły korzyści ekonomiczne w kolejnych okresach, powinny zostać rozliczone w czasie. Najczęściej dotyczy to polis ubezpieczeniowych, abonamentów informatycznych, licencji na oprogramowanie, prenumerat, opłat serwisowych, czynszów zapłaconych z góry oraz usług marketingowych obejmujących kilka miesięcy.' },
        { t: 'h', x: 'Przykład – polisa ubezpieczeniowa' },
        { t: 'p', x: 'Spółka wykupiła 1 października polisę na 12 miesięcy za 12 000 zł. Gdyby cała kwota trafiła w koszty października, wynik za ten miesiąc zostałby zaniżony. Prawidłowo: część dotycząca bieżącego roku idzie w koszty, a część dotycząca kolejnego roku jest wykazywana jako czynne RMK i rozliczana sukcesywnie w kolejnych miesiącach.' },
        { t: 'h', x: 'Bierne rozliczenia międzyokresowe kosztów' },
        { t: 'p', x: 'Przedsiębiorcy często kojarzą RMK wyłącznie z kosztami zapłaconymi z góry. Tymczasem równie ważne są bierne rozliczenia z art. 39 ust. 2 ustawy o rachunkowości, czyli koszty przypadające na dany rok, które nie zostały jeszcze zafakturowane lub opłacone. Ich brak zawyża wynik finansowy.' },
        { t: 'ul', x: ['Czynne RMK (art. 39 ust. 1): zapłacone z góry, dotyczą przyszłości — polisy, licencje, prenumeraty, czynsze z góry, abonamenty IT, opłaty serwisowe', 'Bierne RMK (art. 39 ust. 2): dotyczą bieżącego roku, jeszcze niezafakturowane — niewykorzystane urlopy, premie roczne, energia końca roku, wynagrodzenie biegłego rewidenta'] },
        { t: 'h', x: 'Kiedy nie trzeba rozliczać kosztów w czasie' },
        { t: 'p', x: 'Ustawa dopuszcza uproszczenia. Art. 4 ust. 4 ustawy o rachunkowości pozwala je stosować, jeżeli nie wywierają istotnie ujemnego wpływu na rzetelne przedstawienie sytuacji jednostki. W praktyce niewielkie kwoty mogą być jednorazowo odnoszone w koszty, ale warunki takich uproszczeń powinny zostać opisane w polityce rachunkowości.' },
        { t: 'h', x: 'Najczęstsze błędy' },
        { t: 'p', x: 'W praktyce najczęściej powtarzają się: jednorazowe ujmowanie kosztów dotyczących wielu okresów, brak tworzenia biernych RMK, nieaktualizowanie harmonogramów rozliczeń oraz brak zapisów o uproszczeniach w polityce rachunkowości. To właśnie RMK należą do obszarów najczęściej analizowanych przez biegłych rewidentów, a dodatkowych wskazówek dostarcza Krajowy Standard Rachunkowości nr 6.' },
    ],

    'zamkniecie-roku-bledy': [
        { t: 'p', x: 'Zamknięcie roku obrotowego jest jednym z najważniejszych obowiązków jednostek prowadzących księgi rachunkowe. Jego celem jest rzetelne przedstawienie sytuacji majątkowej, finansowej oraz wyniku finansowego przedsiębiorstwa. Zgodnie z art. 4 ust. 1 ustawy o rachunkowości jednostki są zobowiązane stosować przyjęte zasady rachunkowości w sposób zapewniający rzetelne i jasne przedstawienie sytuacji majątkowej i finansowej oraz wyniku finansowego. Oznacza to, że samo formalne zamknięcie ksiąg nie jest wystarczające, konieczny jest szereg czynności weryfikacyjnych, które pozwolą wykazać wszystkie aktywa, pasywa, przychody i koszty zgodnie z ich rzeczywistą wartością.' },
        { t: 'h', x: 'Błąd 1 – brak lub nieprawidłowa inwentaryzacja' },
        { t: 'p', x: 'Obowiązek inwentaryzacji wynika z art. 26 ustawy o rachunkowości i obejmuje ustalenie rzeczywistego stanu aktywów i pasywów poprzez spis z natury, potwierdzenie sald lub weryfikację dokumentów. W praktyce przedsiębiorcy często skupiają się wyłącznie na spisie magazynu, zapominając o potwierdzeniu należności, zobowiązań czy weryfikacji wartości środków trwałych. Efekt: bilans może wykazywać składniki majątku, które faktycznie nie istnieją albo mają inną wartość niż w księgach.' },
        { t: 'h', x: 'Błąd 2 – niewłaściwe tworzenie rezerw' },
        { t: 'p', x: 'Zgodnie z art. 35d ustawy o rachunkowości jednostki tworzą rezerwy na pewne lub o dużym stopniu prawdopodobieństwa przyszłe zobowiązania, których kwotę można wiarygodnie oszacować. Typowe pominięcia to:' },
        { t: 'ul', x: ['Toczące się postępowania sądowe', 'Niewykorzystane urlopy pracowników', 'Przewidywane kary umowne', 'Koszty likwidacji działalności'] },
        { t: 'p', x: 'Brak utworzenia rezerwy prowadzi do zawyżenia wyniku finansowego i przedstawienia lepszej sytuacji niż rzeczywista.' },
        { t: 'h', x: 'Błąd 3 – brak odpisów aktualizujących należności' },
        { t: 'p', x: 'Art. 35b ustawy o rachunkowości nakłada obowiązek dokonania odpisów aktualizujących wartość należności w przypadku ryzyka ich nieściągalności. Dotyczy to m.in. dłużników w likwidacji lub upadłości, należności znacząco przeterminowanych oraz wierzytelności kwestionowanych przez kontrahenta. Wykazywanie takich należności w pełnej wysokości zawyża aktywa i może prowadzić do błędnych decyzji zarządczych.' },
        { t: 'h', x: 'Błąd 4 – nieprawidłowe rozliczenia międzyokresowe kosztów' },
        { t: 'p', x: 'Zasada współmierności przychodów i kosztów z art. 6 ustawy o rachunkowości oznacza, że koszty powinny być ujmowane w okresie, którego dotyczą, niezależnie od terminu zapłaty. Najczęściej błędy dotyczą polis ubezpieczeniowych, abonamentów i licencji, czynszów opłaconych z góry oraz usług świadczonych na przełomie roku. Nieprawidłowe rozliczenie potrafi znacząco zniekształcić wynik finansowy.' },
        { t: 'h', x: 'Błąd 5 – pominięcie zdarzeń po dniu bilansowym' },
        { t: 'p', x: 'Obowiązek analizy zdarzeń, które wystąpiły po dniu bilansowym, ale przed sporządzeniem sprawozdania, wynika z art. 54 ustawy o rachunkowości. Jeżeli zdarzenie dostarcza informacji o stanie istniejącym na dzień bilansowy, jak upadłość kontrahenta, ujawnienie błędu księgowego czy zakończenie sporu sądowego, jednostka powinna odpowiednio skorygować dane w sprawozdaniu finansowym.' },
        { t: 'h', x: 'Pięć błędów w pigułce' },
        { t: 'ul', x: ['Niepełna inwentaryzacja: nieistniejące składniki majątku w bilansie', 'Brak rezerw: zawyżony wynik finansowy', 'Brak odpisów na należności: zawyżone aktywa', 'Błędne RMK: zniekształcony wynik okresu', 'Pominięte zdarzenia po dniu bilansowym: nieaktualne dane w sprawozdaniu'] },
        { t: 'p', x: 'Prawidłowe zamknięcie roku obrotowego wymaga nie tylko znajomości przepisów, ale doświadczenia w ich praktycznym stosowaniu. W DGC wspieram spółki z o.o. i inne podmioty prowadzące księgi handlowe w przygotowaniu zamknięcia roku, sporządzaniu sprawozdań finansowych, inwentaryzacji oraz analizie zgodności ksiąg z ustawą o rachunkowości. Dzięki temu przedsiębiorcy otrzymują nie tylko poprawne sprawozdanie, ale wiarygodne dane do decyzji biznesowych.' },
    ],

    'wynajem-mieszkania-firmie-najemca': [
        { t: 'p', x: 'Wynajęcie mieszkania na firmę nie oznacza jeszcze automatycznie jednego, prostego skutku podatkowego. Dla najemcy najważniejsze jest najpierw ustalenie, w jakim celu lokal jest wynajmowany. To właśnie cel najmu decyduje potem o kosztach podatkowych, VAT i dokumentach. Inaczej wygląda sytuacja, gdy firma wynajmuje mieszkanie na cele mieszkaniowe pracownika lub zleceniobiorcy, a inaczej, gdy lokal jest wykorzystywany jako biuro, kancelaria, gabinet albo lokal do prowadzenia działalności.' },
        { t: 'h', x: 'Czynsz w kosztach – tylko w części służącej działalności' },
        { t: 'p', x: 'Dla firmy najem jest zwykle kosztem podatkowym, ale tylko w tej części, w jakiej służy działalności. Jeżeli mieszkanie jest wynajęte na potrzeby biznesowe, na przykład jako lokal dla delegowanego pracownika, dla kadry kierowniczej wykonującej zadania w innym mieście albo jako miejsce wykonywania działalności, wydatek może spełniać ogólną definicję kosztu uzyskania przychodu. Trzeba jednak umieć wykazać związek z przychodem lub zabezpieczeniem źródła przychodów. Gdy mieszkanie ma charakter mieszany albo prywatny, bezpieczeństwo podatkowe wyraźnie spada.' },
        { t: 'h', x: 'Dokumentacja – faktura, umowa i KSeF' },
        { t: 'p', x: 'Podstawowy obowiązek najemcy to prawidłowe udokumentowanie wydatku. Jeżeli wynajmującym jest podatnik wystawiający faktury, firma powinna zadbać o fakturę albo, w przypadkach, gdy przepisy to dopuszczają, inny prawidłowy dowód księgowy. Przy najmie w 2026 r. trzeba też pamiętać o KSeF: MF wyjaśnia, że osoba fizyczna wynajmująca firmie lokal jest co do zasady podatnikiem VAT i od 1 kwietnia 2026 r. wchodzi w obowiązkowy KSeF, z przejściowym ułatwieniem do końca 2026 r. przy sprzedaży do 10 000 zł brutto miesięcznie.' },
        { t: 'p', x: 'Od strony formalnej firma powinna mieć umowę najmu wskazującą strony, lokal, cel najmu, czynsz, zasady rozliczania mediów i termin płatności. Przy najmie fakturę wystawia się nie później niż z upływem terminu płatności, co ma znaczenie przy pilnowaniu momentu ujęcia wydatku i ewentualnego VAT.' },
        { t: 'h', x: 'Media, opłaty eksploatacyjne i kaucja' },
        { t: 'p', x: 'Najemca powinien zwrócić uwagę na refakturowane media i opłaty eksploatacyjne. Jeżeli są elementem rozliczenia czynszu, muszą być ujmowane zgodnie z dokumentami od wynajmującego i zgodnie z charakterem podatkowym całej usługi. W księgach trzeba prawidłowo oddzielić czynsz, opłaty dodatkowe i kaucję. Sama kaucja co do zasady nie jest kosztem w momencie wpłaty, bo ma charakter zwrotny, a znaczenia podatkowego nabiera dopiero wtedy, gdy zostaje zatrzymana zgodnie z umową.' },
        { t: 'h', x: 'Przykłady praktyczne' },
        { t: 'p', x: 'Przykład 1 – mieszkanie dla delegowanego pracownika. Spółka wynajmuje mieszkanie na cele mieszkaniowe pracownika delegowanego do innego miasta. Najem jest zwolniony z VAT, więc nie ma VAT do odliczenia, ale czynsz może być kosztem podatkowym, jeśli firma wykaże związek z działalnością.' },
        { t: 'p', x: 'Przykład 2 – mieszkanie na biuro. Firma wynajmuje lokal mieszkalny z przeznaczeniem na biuro. Zwolnienie nie działa, wynajmujący opodatkowuje najem VAT, a najemca może rozważać odliczenie, o ile lokal rzeczywiście służy sprzedaży opodatkowanej.' },
    ],

    'dokument-sad': [
        { t: 'p', x: 'Dokument SAD, czyli Jednolity Dokument Administracyjny, to podstawowy dokument zgłoszenia celnego stosowany w obrocie towarowym z krajami spoza Unii Europejskiej. W praktyce pojawia się przede wszystkim przy imporcie i eksporcie towarów, a dla księgowości jest kluczowym dowodem przy rozliczaniu cła oraz VAT z tytułu importu. Mimo powszechnej cyfryzacji zgłoszeń celnych pojęcie SAD nadal funkcjonuje w obrocie, dlatego warto rozumieć, kto go tworzy, kiedy powstaje i jaką pełni funkcję w rozliczeniach firmy.' },
        { t: 'uwaga', h: 'Kto składa zgłoszenie', x: 'Dokumentu SAD nie tworzy urząd z własnej inicjatywy. Zgłoszenie celne składa zgłaszający: importer, eksporter albo działająca w jego imieniu agencja celna. Obecnie odbywa się to elektronicznie przez systemy KAS, a dokument w układzie SAD jest odzwierciedleniem przyjętego zgłoszenia.' },
        { t: 'h', x: 'Kto tworzy dokument SAD' },
        { t: 'ul', x: ['Importer lub eksporter: może składać zgłoszenie samodzielnie jako zgłaszający', 'Agencja celna: najczęstszy wariant w praktyce, działa jako przedstawiciel na podstawie upoważnienia', 'Organ celno-skarbowy: przyjmuje i weryfikuje zgłoszenie, nie tworzy go za przedsiębiorcę'] },
        { t: 'h', x: 'Kiedy powstaje dokument SAD' },
        { t: 'p', x: 'Dokument powstaje w momencie objęcia towaru procedurą celną, najczęściej przy dopuszczeniu do obrotu w imporcie albo przy wywozie w eksporcie. To wtedy następuje zgłoszenie towaru, wyliczenie należności celnych oraz podstawy VAT z tytułu importu. Data przyjęcia zgłoszenia ma bezpośrednie znaczenie dla rozliczeń, bo wyznacza moment powstania długu celnego i obowiązków podatkowych z nim związanych.' },
        { t: 'h', x: 'SAD w księgowości – do czego służy' },
        { t: 'p', x: 'Dla księgowości dokument celny jest podstawą do ujęcia cła w wartości towaru oraz do rozliczenia VAT z tytułu importu. Zawiera dane o wartości celnej, kursie przeliczeniowym, stawkach i naliczonych należnościach. Bez prawidłowego dokumentu celnego firma nie jest w stanie poprawnie ustalić kosztu zakupu importowanego towaru ani wykazać VAT importowego w ewidencji.' },
        { t: 'h', x: 'Przykłady praktyczne' },
        { t: 'p', x: 'Przykład 1 – import towaru z Chin. Firma sprowadza towar spoza UE. Agencja celna składa zgłoszenie w imieniu importera, towar zostaje dopuszczony do obrotu, a dokument celny staje się podstawą do ujęcia cła w wartości towaru i rozliczenia VAT importowego.' },
        { t: 'p', x: 'Przykład 2 – zakup z Niemiec. Firma kupuje towar od kontrahenta z UE. Dokument SAD w ogóle nie powstaje, to wewnątrzwspólnotowe nabycie towarów, rozliczane na innych zasadach, bez odprawy celnej.' },
        { t: 'p', x: 'Przy imporcie największe błędy nie dotyczą samego zgłoszenia celnego, tylko tego, co dzieje się z dokumentem później: błędnego ujęcia cła, złego kursu albo pominięcia VAT importowego w ewidencji. Pomagam firmom handlującym z krajami spoza UE spiąć dokumenty celne z księgami tak, żeby rozliczenia były spójne i gotowe na kontrolę.' },
        { t: 'zrodlo', x: 'Unijny Kodeks Celny (rozporządzenie UE nr 952/2013) wraz z aktami wykonawczymi · Ustawa o VAT w zakresie importu towarów, w szczególności art. 33 · Systemy zgłoszeń celnych KAS (PUESC).' },
    ],

    'podatek-od-nieruchomosci': [
        { t: 'p', x: 'Podatek od nieruchomości to jedna z najważniejszych danin lokalnych i jednocześnie jedna z tych, przy których przedsiębiorcy popełniają najwięcej błędów formalnych. Płaci go nie tylko właściciel, ale także w określonych sytuacjach posiadacz nieruchomości należącej do Skarbu Państwa albo jednostki samorządu terytorialnego, a czasem również posiadacz zależny, na przykład najemca, jeśli przepisy przewidują taki skutek. Obowiązek podatkowy co do zasady powstaje od pierwszego dnia miesiąca następującego po miesiącu, w którym pojawiły się okoliczności uzasadniające opodatkowanie.' },
        { t: 'uwaga', h: 'Ważne – nowe budynki i budowle', x: 'Dla nowych budynków i budowli działa szczególna reguła: obowiązek zwykle powstaje od 1 stycznia roku następującego po roku zakończenia budowy albo rozpoczęcia użytkowania przed ostatecznym wykończeniem. To jedna z najczęściej pomijanych zasad przy inwestycjach.' },
        { t: 'h', x: 'IN-1 czy DN-1 – dwa modele rozliczenia' },
        { t: 'p', x: 'W praktyce trzeba odróżnić dwa tryby. Osoba fizyczna składa IN-1, czyli informację o nieruchomościach i obiektach budowlanych. Osoba prawna lub jednostka organizacyjna składa DN-1, czyli deklarację na podatek od nieruchomości. Dokument składa się do urzędu gminy właściwego według miejsca położenia nieruchomości.' },
        { t: 'ul', x: ['Osoba fizyczna (IN-1): informacja, termin 14 dni od powstania obowiązku, podatek liczy gmina i wydaje decyzję ustalającą', 'Osoba prawna (DN-1): deklaracja, termin do 31 stycznia roku podatkowego, podatnik liczy sam i wpłaca bez wezwania, decyzji co do zasady nie ma'] },
        { t: 'p', x: 'Różnica pomiędzy informacją a deklaracją nie jest wyłącznie techniczna. Ma bezpośredni wpływ na to, kto dostaje decyzję, a kto ma sam policzyć podatek. O tej zasadzie przedsiębiorcy często zapominają przy przekształceniach, zakupie nieruchomości do spółki albo zmianie sposobu wykorzystania budynku.' },
        { t: 'h', x: 'Stawka firmowa – najwięcej sporów w 2026 r.' },
        { t: 'p', x: 'W 2026 roku szczególne znaczenie ma prawidłowa kwalifikacja części nieruchomości jako związanej z działalnością gospodarczą. To właśnie tutaj pojawia się najwięcej sporów o wyższe stawki podatku. Sam fakt posiadania budynku przez przedsiębiorcę nie zawsze oznacza automatycznie opodatkowanie każdej jego części stawką firmową, wymaga to dokładnej analizy stanu faktycznego i sposobu wykorzystania nieruchomości. W podatku od nieruchomości liczą się nie tylko metry kwadratowe, ale też funkcja gruntu, budynku albo budowli.' },
        { t: 'h', x: 'Przykłady praktyczne' },
        { t: 'p', x: 'Przykład 1 – zakup mieszkania przez osobę fizyczną. Osoba fizyczna kupuje mieszkanie w maju. Składa IN-1 w ciągu 14 dni, a obowiązek podatkowy powstaje od 1 czerwca. Gmina wydaje decyzję ustalającą wysokość podatku, bez decyzji nie ma obowiązku zapłaty.' },
        { t: 'p', x: 'Przykład 2 – nieruchomość w spółce. Spółka z o.o. kupuje halę magazynową. Składa DN-1, sama oblicza podatek i wpłaca go bez czekania na jakiekolwiek pismo z gminy. Brak decyzji nie oznacza braku obowiązku.' },
        { t: 'p', x: 'Przykład 3 – nowy budynek firmowy. Firma kończy budowę biurowca w sierpniu 2026 r. Obowiązek podatkowy powstaje dopiero od 1 stycznia 2027 r., zgodnie ze szczególną regułą dla nowych budynków.' },
        { t: 'p', x: 'Pomagam przeanalizować nieruchomości firmowe i prywatne pod kątem prawidłowej kwalifikacji i stawek. To szczególnie ważne przy lokalach użytkowych, budynkach mieszanych i nieruchomościach wykorzystywanych w biznesie, bo właśnie tam najłatwiej o spór z gminą o stawkę firmową.' },
        { t: 'zrodlo', x: 'Ustawa z 12 stycznia 1991 r. o podatkach i opłatach lokalnych, w szczególności art. 2, art. 3, art. 4 i art. 6 · Oficjalne informacje MF o formularzach IN-1 i DN-1.' },
    ],

    'oplata-produktowa': [
        { t: 'p', x: 'Opłata produktowa nie jest podatkiem lokalnym w ścisłym znaczeniu, ale często pojawia się obok danin samorządowych, bo dotyczy wielu firm wprowadzających produkty w opakowaniach i jest rozliczana z udziałem marszałka województwa. Ustawa o gospodarce opakowaniami i odpadami opakowaniowymi reguluje zasady ustalania i pobierania opłaty produktowej oraz opłaty recyklingowej. Sama opłata produktowa pojawia się wtedy, gdy podmiot nie wykonuje ustawowych obowiązków dotyczących wymaganych poziomów odzysku, recyklingu albo selektywnego zbierania opakowań w zakresie wskazanym w ustawie.' },
        { t: 'uwaga', h: 'Kto wychodzi z inicjatywą', x: 'Nie ma tutaj klasycznej decyzji ustalającej daninę z urzędu na początku roku. Obowiązek najpierw powstaje po stronie przedsiębiorcy, który sam powinien ocenić wykonanie ustawowych poziomów i prawidłowo obliczyć należność. Decyzja marszałka pojawia się dopiero wtedy, gdy organ stwierdzi nieprawidłowość albo zaległość.' },
        { t: 'h', x: 'Dwa kluczowe terminy' },
        { t: 'ul', x: ['Wpłata opłaty produktowej obliczonej na koniec roku: do 15 marca roku następnego, na odrębny rachunek bankowy marszałka województwa', 'Sprawozdanie o produktach, opakowaniach i gospodarowaniu odpadami: do 15 marca za rok poprzedni, elektronicznie w systemie BDO'] },
        { t: 'h', x: 'Rola sprawozdania w BDO' },
        { t: 'p', x: 'Sprawozdanie składane w BDO jest jednym z głównych dokumentów pozwalających ustalić, czy przedsiębiorca osiągnął wymagane poziomy odzysku i recyklingu, i czy w związku z tym powinien wnieść opłatę produktową. Dlatego spójność danych wykazywanych w BDO z prowadzonymi ewidencjami ma tutaj tak duże znaczenie. Rozjazd między sprawozdaniem a rzeczywistością to najprostsza droga do decyzji marszałka określającej zaległość.' },
        { t: 'h', x: 'Kiedy pojawia się decyzja marszałka' },
        { t: 'p', x: 'Jeżeli przedsiębiorca nie wniesie należnej opłaty albo wpłaci ją w zaniżonej wysokości, marszałek województwa może określić zaległość w drodze decyzji. Model działania jest więc odwrotny niż przy wielu podatkach lokalnych: co do zasady przedsiębiorca sam oblicza i wpłaca opłatę, a decyzja jest narzędziem korygującym, nie punktem wyjścia.' },
        { t: 'h', x: 'Rok 2026 – system kaucyjny podnosi ryzyko' },
        { t: 'p', x: 'W 2026 roku temat stał się jeszcze bardziej wrażliwy przez rozbudowę systemu kaucyjnego i kolejne obowiązki związane z opakowaniami. W praktyce przedsiębiorcy bardzo często skupiają się na samym BDO, a zbyt mało uwagi poświęcają temu, czy ich model sprzedaży, struktura opakowań i zawarte umowy rzeczywiście pozwalają uniknąć opłaty produktowej. A to już nie jest kwestia techniczna, tylko realnego ryzyka finansowego.' },
        { t: 'h', x: 'Przykłady praktyczne' },
        { t: 'p', x: 'Przykład 1 – poziomy osiągnięte. Firma wprowadza produkty w opakowaniach i przez umowę z organizacją odzysku osiąga wymagane poziomy recyklingu. Składa sprawozdanie w BDO do 15 marca. Opłata produktowa nie występuje, bo obowiązki ustawowe zostały wykonane.' },
        { t: 'p', x: 'Przykład 2 – poziomy nieosiągnięte. Firma nie osiągnęła wymaganego poziomu odzysku. Na koniec roku sama oblicza opłatę produktową i wpłaca ją do 15 marca na rachunek marszałka, równolegle składając sprawozdanie w BDO.' },
        { t: 'p', x: 'Przykład 3 – zaniżona wpłata. Firma wpłaciła opłatę w zaniżonej wysokości przez błędne dane o masie opakowań. Marszałek stwierdza rozbieżność i określa zaległość w drodze decyzji. Dochodzi korekta i odsetki.' },
        { t: 'p', x: 'Pomagam firmom połączyć dane księgowe, magazynowe i środowiskowe tak, aby opłata produktowa nie była rozliczana na wyczucie, lecz na podstawie uporządkowanych ewidencji i prawidłowych sprawozdań w BDO.' },
        { t: 'zrodlo', x: 'Ustawa z 13 czerwca 2013 r. o gospodarce opakowaniami i odpadami opakowaniowymi, w szczególności art. 34, art. 36 i art. 37 · Zasady sprawozdawczości w systemie BDO.' },
    ],

    'system-sent': [
        { t: 'p', x: 'System SENT, czyli System Elektronicznego Nadzoru Transportu, nie dotyczy wszystkich przewozów, ale tylko tych, które ustawodawca objął monitorowaniem. W praktyce służy on do nadzoru nad drogowym i kolejowym przewozem określonych towarów oraz nad obrotem paliwami opałowymi. PUESC wyjaśnia, że SENT obejmuje przewozy na terytorium Polski zarówno wtedy, gdy transport zaczyna się i kończy w Polsce, jak i wtedy, gdy zaczyna się lub kończy poza Polską, a nawet gdy przebiega tranzytem przez Polskę.' },
        { t: 'uwaga', h: 'Ważne – rozszerzenie od 17 marca 2026 r.', x: 'SENT to już od dawna nie tylko system dla paliw. Ministerstwo Finansów potwierdziło, że od 17 marca 2026 r. SENT obejmuje również określone przewozy odzieży, dodatków odzieżowych, odzieży używanej i obuwia, po przekroczeniu wskazanych progów wagowych lub ilościowych.' },
        { t: 'h', x: 'Kto musi korzystać z SENT' },
        { t: 'p', x: 'Z SENT muszą korzystać przede wszystkim podmioty, które wysyłają, odbierają albo przewożą towary objęte systemem, a także podmioty dokonujące obrotu paliwem opałowym oraz wykonujące międzynarodowy przewóz rzeczy. W takich przypadkach istnieje obowiązek dokonania zgłoszenia do rejestru SENT, a następnie jego uzupełniania i aktualizacji. Po stronie przewoźnika dochodzi jeszcze obowiązek zapewnienia przekazywania danych geolokalizacyjnych środka transportu.' },
        { t: 'h', x: 'Trzy role w przewozie – każdy ma swoje obowiązki' },
        { t: 'ul', x: ['Podmiot wysyłający: inicjuje zgłoszenie w rejestrze SENT', 'Przewoźnik: uzupełnia dane o środku transportu i zapewnia geolokalizację', 'Podmiot odbierający: potwierdza odbiór towaru'] },
        { t: 'p', x: 'PUESC udostępnia odrębne formularze dla różnych ról i wariantów przewozu: przewozów rozpoczynających się w Polsce, przywozu do Polski, tranzytu przez Polskę oraz międzynarodowego przewozu drogowego rzeczy.' },
        { t: 'h', x: 'Progi i wyłączenia – nie każdy transport podlega zgłoszeniu' },
        { t: 'p', x: 'Nie każdy transport każdej ilości towaru trzeba zgłaszać. Znaczenie mają zarówno rodzaj towaru, jak i progi ilościowe lub wagowe, a także ustawowe i rozporządzeniowe wyłączenia. Przy rozszerzeniu SENT na odzież i obuwie od 17 marca 2026 r. wprowadzono również wyłączenia, m.in. dla części przesyłek pocztowych oraz niektórych modeli logistycznych typu fulfillment spełniających warunki wskazane przez MF.' },
        { t: 'h', x: 'Rejestracja w PUESC – bez tego ani rusz' },
        { t: 'p', x: 'Od strony organizacyjnej firma musi działać przez PUESC. Dla nowych obowiązków od marca 2026 r. trzeba zarejestrować albo zaktualizować dane firmy w obszarze Monitorowanie przewozu oraz powiązać osobę działającą w imieniu firmy z odpowiednim uprawnieniem SENT. Bez tego terminowe składanie zgłoszeń może być po prostu niemożliwe.' },
        { t: 'h', x: 'Przykłady praktyczne' },
        { t: 'p', x: 'Przykład 1 – hurtownia odzieży od marca 2026. Firma wysyła transport odzieży przekraczający progi wagowe określone w przepisach. Od 17 marca 2026 r. musi zgłosić przewóz w SENT jako podmiot wysyłający, mimo że nie ma nic wspólnego z paliwami.' },
        { t: 'p', x: 'Przykład 2 – przewoźnik w tranzycie. Przewoźnik wykonuje transport towaru objętego SENT przez Polskę tranzytem. Mimo że ani nadawca, ani odbiorca nie są w Polsce, przewoźnik ma obowiązki w systemie, w tym przekazywanie danych geolokalizacyjnych.' },
        { t: 'p', x: 'Przykład 3 – mała przesyłka poniżej progu. Firma wysyła niewielką partię towaru poniżej progów ilościowych. Zgłoszenie SENT nie jest wymagane, ale trzeba umieć wykazać, że próg faktycznie nie został przekroczony.' },
        { t: 'p', x: 'Największy błąd przy SENT polega na tym, że firmy patrzą tylko na branżę, a nie na konkretny towar, trasę i swoją rolę w przewozie. Tymczasem obowiązek może dotyczyć nie tylko przewoźnika, ale też nadawcy czy odbiorcy. Pomagam ustalić, czy dana firma podlega SENT i jak uporządkować zgłoszenia w PUESC.' },
        { t: 'zrodlo', x: 'Ustawa z 9 marca 2017 r. o systemie monitorowania drogowego i kolejowego przewozu towarów oraz obrotu paliwami opałowymi · Akty wykonawcze wydane na jej podstawie, w tym rozporządzenia rozszerzające katalog towarów objętych SENT w 2025 i 2026 r.' },
    ],

    'podatek-lesny': [
        { t: 'p', x: 'Podatek leśny to kolejny podatek lokalny, który bardzo często jest mylony z podatkiem od nieruchomości albo traktowany jako marginalny obowiązek. Tymczasem dla właścicieli i posiadaczy gruntów oznaczonych w ewidencji symbolem Ls ma on bardzo konkretne skutki. Punkt wyjścia jest zawsze ten sam: najpierw trzeba ustalić klasyfikację gruntu w ewidencji, a dopiero później analizować formularze, terminy i sposób zapłaty.' },
        { t: 'uwaga', h: 'Najczęstszy punkt pomyłek', x: 'Opodatkowaniu podlegają grunty sklasyfikowane jako las Ls, ale nie te zajęte na prowadzenie działalności gospodarczej innej niż leśna. W takim przypadku wchodzi już w grę podatek od nieruchomości.' },
        { t: 'h', x: 'Kto płaci podatek leśny' },
        { t: 'p', x: 'Podatek leśny płaci właściciel lasu, posiadacz samoistny, użytkownik wieczysty oraz posiadacz lasu należącego do Skarbu Państwa albo jednostki samorządu terytorialnego. Jeżeli las pozostaje we współwłasności lub współposiadaniu kilku osób, obowiązek podatkowy obciąża ich solidarnie.' },
        { t: 'h', x: 'Jak liczona jest stawka' },
        { t: 'p', x: 'Podstawą obliczenia jest powierzchnia lasu w hektarach fizycznych wynikająca z ewidencji gruntów i budynków. Stawka ma charakter ustawowy i zależy od średniej ceny sprzedaży drewna ogłaszanej przez GUS:' },
        { t: 'ul', x: ['Las standardowy: równowartość 0,220 m³ drewna', 'Las w rezerwacie przyrody lub parku narodowym: 50% stawki, czyli 0,110 m³ drewna'] },
        { t: 'h', x: 'IL-1 czy DL-1 – kto co składa i kto dostaje decyzję' },
        { t: 'ul', x: ['Osoba fizyczna (IL-1): informacja o lasach, termin 14 dni od zdarzenia, organ wydaje decyzję ustalającą, płatność w 4 ratach (15 marca, 15 maja, 15 września, 15 listopada)', 'Osoba prawna (DL-1): deklaracja na podatek leśny, termin do 15 stycznia lub 14 dni od powstania obowiązku, podatnik sam oblicza bez wezwania, płatność w 12 ratach do 15. dnia każdego miesiąca'] },
        { t: 'p', x: 'Jeżeli roczna kwota podatku nie przekracza 100 zł, podatek płaci się jednorazowo w terminie pierwszej raty. Przy niewielkich areałach leśnych to bardzo częsty przypadek.' },
        { t: 'h', x: 'Przykłady praktyczne' },
        { t: 'p', x: 'Przykład 1 – osoba fizyczna z 2 ha lasu. Właściciel gruntu Ls składa IL-1 w ciągu 14 dni od nabycia. Gmina wydaje decyzję ustalającą wysokość podatku. Płatność w 4 ratach, a jeśli roczna kwota nie przekracza 100 zł, jednorazowo przy pierwszej racie.' },
        { t: 'p', x: 'Przykład 2 – spółka z gruntem leśnym. Spółka z o.o. posiadająca grunt Ls składa DL-1 do 15 stycznia, sama oblicza podatek i wpłaca go w 12 miesięcznych ratach bez czekania na jakiekolwiek pismo z gminy.' },
        { t: 'p', x: 'Przykład 3 – las zajęty pod działalność. Część gruntu Ls została zajęta pod parking firmowy. Ta część nie podlega już podatkowi leśnemu, lecz podatkowi od nieruchomości według stawek dla działalności gospodarczej.' },
        { t: 'p', x: 'Przy podatku leśnym wszystko zaczyna się od ewidencji gruntów, a nie od formularza. Błędna klasyfikacja albo pominięcie części gruntu zajętej pod działalność to najczęstsze źródła sporów z gminą. Pomagam ustalić, który podatek faktycznie dotyczy danego gruntu i jak prawidłowo go rozliczyć.' },
        { t: 'zrodlo', x: 'Ustawa z 30 października 2002 r. o podatku leśnym, w szczególności art. 1, art. 2, art. 3, art. 4 i art. 6 · Rozporządzenie Ministra Finansów w sprawie wzorów informacji o lasach (IL-1) i deklaracji na podatek leśny (DL-1).' },
    ],

    'hodowla-pajakow-podatki': [
        { t: 'p', x: 'Hodowla pająków na sprzedaż jest podatkowo najbardziej złożona spośród hodowli zwierząt egzotycznych. Wynika to z tego, że przepisy nie wymieniają pająków tak wprost jak królików czy psów rasowych. Dlatego przy tej działalności najpierw trzeba ustalić, czy dana hodowla mieści się w katalogu działów specjalnych produkcji rolnej, czy można ją traktować jako działalność rolniczą, czy też w praktyce będzie to zwykła działalność gospodarcza. Właśnie ten pierwszy etap decyduje o wszystkim: od formy rozliczenia, przez PIT-6, aż po zasady VAT.' },
        { t: 'uwaga', h: 'Ważne', x: 'Ustawa o PIT zawiera zamknięty katalog działów specjalnych produkcji rolnej. Wymienia m.in. hodowlę entomofagów oraz chów innych zwierząt poza gospodarstwem rolnym. Jeżeli hodowla pająków nie mieści się w żadnej kategorii z załącznika nr 2, nie można automatycznie uznać jej za dział specjalny tylko dlatego, że dotyczy egzotycznych zwierząt.' },
        { t: 'h', x: 'Trzy pytania, które decydują o kwalifikacji' },
        { t: 'ul', x: ['Czy hodowane gatunki i cel produkcji pozwalają zakwalifikować działalność do działów specjalnych, np. jako hodowlę entomofagów?', 'Jeżeli nie, czy model spełnia cechy działalności rolniczej, czyli własny chów i hodowla, a nie zwykły obrót okazami?', 'Czy sprzedaż nie ma w praktyce charakteru typowo handlowego, który przesuwa całość do działalności gospodarczej?'] },
        { t: 'h', x: 'Trzy możliwe scenariusze podatkowe' },
        { t: 'ul', x: ['Hodowla entomofagów, np. do ochrony upraw: dział specjalny produkcji rolnej, PIT-6, księgi lub normy szacunkowe, zaliczki z decyzji US', 'Własny chów, ale poza katalogiem działów specjalnych: możliwa działalność rolnicza, przychody poza PIT, wymaga dużej ostrożności', 'Kupno okazów i odsprzedaż: działalność gospodarcza, zwykłe zasady opodatkowania PIT'] },
        { t: 'h', x: 'Największe ryzyko podatkowe' },
        { t: 'p', x: 'Ryzyko pojawia się wtedy, gdy ktoś kupuje gotowe okazy i po prostu sprzedaje je dalej. W takim modelu trudno mówić o własnym chowie czy hodowli. Jeżeli nie ma rzeczywistego procesu hodowlanego, fiskus może zakwalifikować działalność jako zwykłą działalność gospodarczą. Dlatego tak ważne jest udokumentowanie pochodzenia okazów, procesu rozmnażania, czasu przetrzymywania i faktycznego modelu działalności.' },
        { t: 'h', x: 'CITES i legalność obrotu' },
        { t: 'p', x: 'Poza podatkami dochodzą kwestie legalności samego obrotu. Przy części gatunków egzotycznych zastosowanie mogą mieć przepisy o CITES i ochronie przyrody. W praktyce może być potrzebne udokumentowanie legalnego pochodzenia zwierząt, źródła ich nabycia i miejsca hodowli. Poprawne rozliczenie podatku nie wystarczy, jeśli sam obrót danym gatunkiem jest nielegalny albo niewłaściwie udokumentowany.' },
        { t: 'h', x: 'VAT przy hodowli pająków' },
        { t: 'p', x: 'Ustawa o VAT szeroko rozumie działalność rolniczą, ale przy pająkach najpierw trzeba ustalić, czy w ogóle mamy do czynienia z takim modelem. Jeżeli tak, możliwe może być korzystanie z zasad właściwych dla rolnika ryczałtowego. Jeżeli działalność ma charakter handlowy albo nie mieści się w działalności rolniczej, zasady VAT ocenia się według zwykłych reguł.' },
        { t: 'h', x: 'Przykłady praktyczne' },
        { t: 'p', x: 'Przykład 1 – entomofagi do ochrony upraw. Hodowla pająków wykorzystywanych jako organizmy pożyteczne w biologicznej ochronie upraw. Najbliżej kwalifikacji jako dział specjalny produkcji rolnej, obowiązuje PIT-6 i rozliczenie jak przy innych działach specjalnych.' },
        { t: 'p', x: 'Przykład 2 – rozmnażanie egzotycznych pająków. Hodowca rozmnaża egzotyczne pająki i okazjonalnie sprzedaje młode, ale model nie mieści się w katalogu działów specjalnych. Trzeba zbadać, czy to jeszcze działalność rolnicza, granica bywa cienka.' },
        { t: 'p', x: 'Przykład 3 – kupno i odsprzedaż. Sprzedawca kupuje okazy i odsprzedaje je dalej bez własnego procesu hodowlanego. Najczęściej będzie to już działalność gospodarcza z pełnym opodatkowaniem.' },
        { t: 'p', x: 'Przy hodowli pająków nie warto działać na skróty. To obszar, w którym bardzo łatwo pomylić działalność rolniczą z handlem, a dodatkowo dochodzą przepisy środowiskowe i dotyczące ochrony gatunków. Pomagam uporządkować takie modele sprzedaży od strony PIT, VAT i dokumentacji, bo tu szczegóły mają naprawdę duże znaczenie.' },
        { t: 'zrodlo', x: 'Art. 2 ust. 1–3a, art. 15, art. 24 ust. 4, art. 43 ustawy o PIT oraz załącznik nr 2 do ustawy o PIT · Art. 2 pkt 15, 19 i 20 oraz art. 43 ust. 1 pkt 3 ustawy o VAT · Przepisy o CITES i ochronie przyrody dotyczące gatunków objętych ograniczeniami obrotu.' },
    ],

    'oplaty-srodowiskowe-wykaz-progi': [
        { t: 'p', x: 'Opłaty za korzystanie ze środowiska wynikają z ustawy Prawo ochrony środowiska i obejmują m.in. emisję zanieczyszczeń do powietrza czy składowanie odpadów. Ich rozliczenie odbywa się wobec marszałka województwa, a nie wobec gminy. Kluczowa zasada to brak decyzji wymiarowej z urzędu: podmiot sam ustala zakres korzystania ze środowiska i sam przygotowuje wykaz. Ministerstwo Klimatu i Środowiska wprost wskazuje, że raz w roku do 31 marca podmioty korzystające ze środowiska przedkładają marszałkom województw wykazy za rok poprzedni, zawierające informacje o zakresie korzystania ze środowiska oraz o wysokości należnych opłat.' },
        { t: 'uwaga', h: 'Ważne – kolejność ma znaczenie', x: 'Przy emisji do powietrza wysokość opłaty ustala się na podstawie rocznych rzeczywistych emisji z raportu do Krajowej bazy KOBiZE, który trzeba złożyć do końca lutego za rok poprzedni. Dopiero na podstawie tego raportu sporządza się wykaz i liczy opłatę.' },
        { t: 'h', x: 'Progi zwalniające – kiedy nie trzeba płacić ani składać wykazu' },
        { t: 'p', x: 'To właśnie progi są najważniejszą informacją praktyczną dla mniejszych przedsiębiorców. Ustawa przewiduje dwa odrębne progi dla każdego rodzaju korzystania ze środowiska:' },
        { t: 'ul', x: ['Do 100 zł rocznej opłaty: brak obowiązku wpłaty i brak obowiązku wykazu', 'Od 101 do 800 zł: brak obowiązku wpłaty, ale wykaz trzeba złożyć', 'Powyżej 800 zł: obowiązek wpłaty i obowiązek wykazu'] },
        { t: 'p', x: 'Progi dotyczą każdego rodzaju korzystania ze środowiska osobno. Jeżeli firma ma kilka tytułów, np. emisja z kotłów i ze środków transportu, każdy liczy się odrębnie. Brak wpłaty nie zwalnia jednak z obowiązku obliczenia i sprawdzenia, czy próg nie jest przekroczony.' },
        { t: 'h', x: 'Co zawiera wykaz i gdzie się go składa' },
        { t: 'p', x: 'Wzory wykazów określa odrębne rozporządzenie Ministra Klimatu. Wykaz zawiera m.in. informacje o rodzaju i zakresie korzystania ze środowiska, ilości wprowadzonych zanieczyszczeń lub składowanych odpadów oraz o wyliczonej wysokości opłaty. Składa się go do urzędu marszałkowskiego właściwego ze względu na miejsce korzystania ze środowiska, a przy emisji z urządzeń obowiązuje właściwość według miejsca rejestracji podmiotu.' },
        { t: 'h', x: 'Przykłady praktyczne' },
        { t: 'p', x: 'Przykład 1 – mała firma, niska emisja. Firma ma jeden kocioł gazowy. Po przeliczeniu emisji za rok wychodzi opłata 80 zł. Nie składa wykazu i nie wpłaca, bo oba progi nie są przekroczone. Ale musi to policzyć i udokumentować.' },
        { t: 'p', x: 'Przykład 2 – firma transportowa. Firma ma flotę pojazdów. Emisja z eksploatacji daje opłatę 450 zł. Nie płaci, bo to poniżej 800 zł, ale składa wykaz do marszałka, bo to powyżej 100 zł. Raport do KOBiZE musi być złożony do końca lutego, zanim powstanie wykaz.' },
        { t: 'p', x: 'Przykład 3 – zakład z wysoką emisją. Emisja z procesu produkcyjnego przekracza 800 zł opłaty. Obowiązek złożenia wykazu do 31 marca i wpłaty opłaty do tego samego terminu. Brak działania może skutkować naliczeniem odsetek i ewentualną kontrolą.' },
        { t: 'p', x: 'Przy opłatach środowiskowych największe ryzyko pojawia się nie u dużych zakładów, które mają wyspecjalizowane służby, ale u średnich firm, które nie wiedzą, że ich instalacja, kotłownia albo flota pojazdów generuje obowiązek środowiskowy. Pomagam połączyć dane księgowe i eksploatacyjne z prawidłowym wykazem do marszałka.' },
        { t: 'zrodlo', x: 'Ustawa z 27 kwietnia 2001 r. Prawo ochrony środowiska, art. 273 i nast. oraz art. 289 (progi zwalniające) · Rozporządzenie Rady Ministrów w sprawie jednostkowych stawek opłat · Obwieszczenie Ministra Klimatu i Środowiska w sprawie stawek na 2026 r. z 6 sierpnia 2025 r.' },
    ],

    'oplata-paliwowa-opal': [
        { t: 'p', x: 'Opłata paliwowa bywa wrzucana do jednego worka z podatkami lokalnymi, ale z prawnego punktu widzenia to zupełnie inna danina. To opłata publicznoprawna związana z wprowadzaniem na rynek krajowy określonych paliw silnikowych i gazu wykorzystywanego do napędu silników spalinowych. Stanowi przychód Krajowego Funduszu Drogowego i Funduszu Kolejowego, a nie budżetu gminy. Jej konstrukcja, właściwość organów i tryb rozliczeń są zupełnie inne niż przy podatku od nieruchomości czy podatku od środków transportowych.' },
        { t: 'uwaga', h: 'Kogo to nie dotyczy', x: 'Zwykły kierowca ani przeciętny przedsiębiorca kupujący paliwo na stacji nie składa samodzielnie formularza OPAL. Opłata paliwowa dotyczy przede wszystkim producentów, importerów i nabywców wprowadzających paliwa na rynek krajowy.' },
        { t: 'h', x: 'Kto płaci opłatę paliwową' },
        { t: 'p', x: 'Obowiązek dotyczy podmiotów, które wprowadzają na rynek krajowy paliwa silnikowe lub gaz objęty przepisami. W praktyce są to przede wszystkim:' },
        { t: 'ul', x: ['Krajowy producent paliw: tak', 'Importer paliw: tak', 'Nabywca wewnątrzwspólnotowy paliw: tak', 'Przedsiębiorca kupujący paliwo na stacji: nie'] },
        { t: 'h', x: 'Formularz OPAL i termin rozliczenia' },
        { t: 'p', x: 'Podmiot objęty obowiązkiem składa informację elektronicznie na formularzu OPAL za pośrednictwem platformy PUESC. Standardowy termin to do 25. dnia miesiąca następującego po miesiącu, w którym powstał obowiązek zapłaty. W tym samym terminie następuje wpłata opłaty.' },
        { t: 'p', x: 'Dla importerów zasada jest inna: właściwym organem jest naczelnik urzędu celno-skarbowego właściwy ze względu na miejsce powstania długu celnego, a informację składa się w terminie 10 dni od dnia odprawy celnej. To pokazuje, jak mocno opłata paliwowa jest powiązana z przepisami akcyzowymi i celnymi, a nie z typowym systemem podatków lokalnych.' },
        { t: 'h', x: 'Czym opłata paliwowa różni się od podatku lokalnego' },
        { t: 'ul', x: ['Beneficjent: Krajowy Fundusz Drogowy i Fundusz Kolejowy, a nie budżet gminy', 'Organ: urząd celno-skarbowy i platforma PUESC, a nie wójt, burmistrz czy prezydent', 'Formularz: OPAL na PUESC, a nie IN-1, DN-1 czy DT-1', 'Kto płaci w praktyce: producenci, importerzy i nabywcy wewnątrzwspólnotowi, a nie właściciele nieruchomości, pojazdów i gruntów'] },
        { t: 'h', x: 'Przykłady praktyczne' },
        { t: 'p', x: 'Przykład 1 – importer paliwa. Firma importuje paliwo silnikowe spoza UE. Przy odprawie celnej powstaje obowiązek opłaty paliwowej. Formularz OPAL składa się do właściwego urzędu celno-skarbowego w terminie 10 dni od odprawy. Nie wysyła się formularza do gminy.' },
        { t: 'p', x: 'Przykład 2 – firma transportowa. Firma transportowa tankuje pojazdy na stacjach paliw. Nie składa OPAL, bo opłata paliwowa jest już wliczona w cenę paliwa przez podmiot wprowadzający je na rynek. Firma płaci ją pośrednio, kupując paliwo.' },
        { t: 'p', x: 'Opłata paliwowa nie jest podatkiem lokalnym i nie rozlicza się jej przez gminę. Dla podmiotów z branży paliwowej i importowej błąd formalny w terminie albo złe przypisanie organu może kosztować znacznie więcej niż przy zwykłych rozliczeniach lokalnych. Pomagam firmom z elementem paliwowym i akcyzowym w prawidłowym rozliczeniu tej opłaty.' },
        { t: 'zrodlo', x: 'Ustawa z 27 października 1994 r. o autostradach płatnych oraz o Krajowym Funduszu Drogowym, przepisy dotyczące opłaty paliwowej · Platforma PUESC i formularz OPAL · Ustawa o podatku akcyzowym w zakresie powiązań z obowiązkiem opłaty paliwowej przy imporcie.' },
    ],

    'cit-estonski-efektywna-stopa': [
        { t: 'p', x: 'Jednym z najczęstszych pytań przy analizie CIT estońskiego jest: ile realnie wynosi łączne opodatkowanie spółki i wspólnika? Na poziomie samej spółki ryczałt wynosi 10% albo 20%, ale przy wypłacie podzielonego zysku dochodzi jeszcze PIT wspólnika. I właśnie tu zaczyna się ta część kalkulacji, którą wiele opracowań pomija albo upraszcza. Ustawa o PIT daje wspólnikowi możliwość pomniejszenia tego PIT o część ryczałtu zapłaconego przez spółkę, i to właśnie ten mechanizm odliczenia decyduje o faktycznej efektywnej stopie opodatkowania.' },
        { t: 'uwaga', h: 'Ważne', x: 'Efektywna stopa około 20% i 25% dotyczy klasycznej wypłaty podzielonego zysku. Przy ukrytych zyskach, wydatkach niezwiązanych z działalnością albo innych kategoriach dochodu z art. 28m ustawy o CIT mechanizm odliczenia działa inaczej albo nie działa w ogóle. Podane wartości nie są więc gwarancją na każdą wypłatę ze spółki.' },
        { t: 'h', x: 'Mechanizm odliczenia PIT wspólnika' },
        { t: 'p', x: 'Art. 30a ust. 19 ustawy o PIT pozwala wspólnikowi pomniejszyć zryczałtowany podatek od dywidendy o część ryczałtu zapłaconego przez spółkę. Kwota odliczenia zależy od stawki ryczałtu:' },
        { t: 'ul', x: ['Ryczałt spółki 10% (mały podatnik): odliczenie 90% iloczynu udziału wspólnika i należnego ryczałtu', 'Ryczałt spółki 20% (pozostali podatnicy): odliczenie 70% iloczynu udziału wspólnika i należnego ryczałtu'] },
        { t: 'h', x: 'Efektywna stopa łączna przy wypłacie zysku' },
        { t: 'ul', x: ['Mały podatnik, ryczałt 10%: około 20%', 'Pozostali podatnicy, ryczałt 20%: około 25%'] },
        { t: 'p', x: 'Takie wartości potwierdzają zarówno przepisy, jak i oficjalne materiały MF. Warto jednak pamiętać, że są to wartości przybliżone, bo dokładna kwota odliczenia zależy od udziału wspólnika, wysokości ryczałtu i faktycznej kwoty dywidendy.' },
        { t: 'h', x: 'Porównanie z klasycznym CIT' },
        { t: 'ul', x: ['CIT 9% (mały podatnik) plus PIT 19% od dywidendy: około 26,3%', 'CIT 19% plus PIT 19% od dywidendy: około 34,4%', 'CIT estoński 10% plus PIT z odliczeniem 90%: około 20%', 'CIT estoński 20% plus PIT z odliczeniem 70%: około 25%'] },
        { t: 'h', x: 'Kiedy efektywna stopa może być wyższa' },
        { t: 'p', x: 'Podawana efektywna stopa około 20% lub 25% zakłada klasyczną wypłatę podzielonego zysku. Są sytuacje, kiedy realne opodatkowanie jest wyższe:' },
        { t: 'ul', x: ['Ukryte zyski: ryczałt naliczany od całości świadczenia, a mechanizm odliczenia PIT działa inaczej niż przy dywidendzie', 'Wydatki niezwiązane z działalnością: opodatkowane ryczałtem bez prawa do odliczenia PIT po stronie wspólnika', 'Dochód z tytułu zysku netto przy wyjściu z systemu: odrębna kategoria, opodatkowana ryczałtem w roku zakończenia estońskiego CIT'] },
        { t: 'p', x: 'Efektywna stopa około 20% to nie obietnica. To wynik mechanizmu odliczenia przy klasycznej dywidendzie. Przy każdej innej kategorii dochodu z CIT estońskiego trzeba liczyć od nowa. Pomagam spółkom zrozumieć, ile realnie zapłacą podatku, przed wejściem w system, a nie po pierwszej wypłacie.' },
        { t: 'zrodlo', x: 'Art. 30a ust. 19 ustawy o PIT (mechanizm odliczenia PIT wspólnika) · Art. 28o ust. 1 ustawy o CIT (stawki ryczałtu 10% i 20%) · Oficjalne materiały MF o efektywnej stopie opodatkowania w ryczałcie od dochodów spółek.' },
    ],

    'skladki-preferencyjne-2026': [
        { t: 'p', x: 'Składki preferencyjne to kolejny etap po uldze na start albo rozwiązanie dla przedsiębiorcy, który z ulgi na start zrezygnował wcześniej. W 2026 roku zasada pozostaje taka sama: przez 24 pełne miesiące kalendarzowe przedsiębiorca może opłacać składki na ubezpieczenia społeczne od obniżonej podstawy, która nie może być niższa niż 30% minimalnego wynagrodzenia za pracę. W 2026 r. obniżona podstawa wynosi 1 441,80 zł, czyli 30% minimalnego wynagrodzenia w wysokości 4 806 zł.' },
        { t: 'uwaga', h: 'Ważne', x: 'Składki preferencyjne obniżają wyłącznie składki społeczne. Składka zdrowotna jest opłacana na zasadach ogólnych, niezależnie od korzystania z preferencji. Część przedsiębiorców błędnie zakłada, że preferencyjny ZUS obniża wszystkie obciążenia naraz.' },
        { t: 'h', x: 'Kto ma prawo do składek preferencyjnych' },
        { t: 'ul', x: ['Brak prowadzenia działalności w ostatnich 60 miesiącach kalendarzowych', 'Brak wykonywania czynności dla byłego pracodawcy pokrywających się z etatem', 'Brak statusu osoby współpracującej'] },
        { t: 'h', x: 'Jak liczyć 24 miesiące' },
        { t: 'p', x: 'Tu pojawia się najczęstszy błąd. Sposób liczenia zależy od tego, czy wcześniej była ulga na start:' },
        { t: 'ul', x: ['Pełne 6 miesięcy ulgi na start: od dnia następnego po upływie ulgi na start', 'Rezygnacja z ulgi na start wcześniej lub brak ulgi: od dnia objęcia ubezpieczeniami społecznymi wskazanego we wniosku, nie wcześniej niż od dnia zgłoszenia'] },
        { t: 'h', x: 'Co po składkach preferencyjnych' },
        { t: 'p', x: 'Po wyczerpaniu 24 miesięcy przedsiębiorca przechodzi na pełne składki, chyba że spełnia warunki Małego ZUS Plus, wtedy może skorzystać z kolejnej preferencji, tym razem opartej na dochodzie z działalności. Warto planować tę ścieżkę z wyprzedzeniem, bo Mały ZUS Plus wymaga spełnienia odrębnych warunków, w tym limitu przychodów za poprzedni rok (120 000 zł).' },
        { t: 'h', x: 'Przykłady praktyczne' },
        { t: 'p', x: 'Przykład 1 – pełna ścieżka preferencji. Przedsiębiorca startuje 1 marca 2026 r. Korzysta z ulgi na start przez 6 miesięcy (marzec–sierpień). Od września 2026 r. wchodzi na składki preferencyjne przez 24 miesiące, do sierpnia 2028 r. Jeśli spełni warunki, od 2029 r. może wejść na Mały ZUS Plus.' },
        { t: 'p', x: 'Przykład 2 – błąd przy liczeniu okresu. Przedsiębiorca myli datę wejścia na składki preferencyjne i zgłasza się o miesiąc za późno. Traci jeden miesiąc preferencji i nadpłaca pełne składki za ten miesiąc. Drobny błąd formalny, realny koszt finansowy.' },
        { t: 'p', x: 'Przy przejściu z ulgi na start na składki preferencyjne pojawia się najwięcej błędów formalnych. Pomagam uporządkować zgłoszenia, terminy i kody ZUS tak, żeby przedsiębiorca nie tracił prawa do obniżonych składek przez zwykłe przeoczenie.' },
        { t: 'zrodlo', x: 'Art. 18a ustawy z 13 października 1998 r. o systemie ubezpieczeń społecznych · Art. 18aa ustawy o SUS (przejście z ulgi na start) · Aktualne informacje ZUS o składkach przedsiębiorców w 2026 r. (obniżona podstawa 1 441,80 zł).' },
    ],
};

export default tresci;
